<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Descrição do site -->
  <meta name="description" content="Barbearia">
  <!-- palavras chave -->
  <meta name="keywords" content="corte, cabelo, barba, progressiva, penteados">
  <!-- autor do site -->

  <meta name="autor" content="Arthur Costa">

  <!-- Open Graph -->
  <meta property="og:title" content="Jho's Barbershop">
  <meta property="og:description" content="Barbearia">
  <meta property="og:image" content="https://">
  <meta property="og:type" content="website">
  <!-- Links dos ICONS FAVICOM -->
  <!-- Favicon package generated by Favicon.im Converter -->
  <link rel="icon" type="image/x-icon" href="assets/icon/favicon.ico">
  <link rel="icon" type="image/png" sizes="16x16" href="assets/icon/favicon-16x16.png">
  <link rel="icon" type="image/png" sizes="32x32" href="assets/icon/favicon-32x32.png">
  <link rel="apple-touch-icon" sizes="180x180" href="assets/icon/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="192x192" href="assets/icon/android-chrome-192x192.png">
  <link rel="icon" type="image/png" sizes="512x512" href="assets/icon/android-chrome-512x512.png">
  <meta name="theme-color" content="#ffffff">


  <title>Jho's Barbershop</title>
  <!-- Reset limpa os estilos -->
  <link rel="stylesheet" href="css/reset.css">

  <!-- slick -->
  <link rel="stylesheet" href="css/slick.css">

  <link rel="stylesheet" href="css/slick-theme.css">

  <!-- Animate CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
  <!-- Estilo -->
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/responsive.css">


</head>

<body>
  <!-- cabeçalho -->

  <?php require_once('conteudo/topo.php') ?>

  <!-- Corpo -->
  <main>
    <!-- inicio banner -->
    <?php require_once('conteudo/banner.php'); ?>
    <!-- fim banner -->

    <!-- inicio historia jho -->

    <?php require_once('conteudo/historia-jho.php'); ?>

    <!-- fim historia jho -->

    <!-- inicio serviços -->

    <?php require_once('conteudo/servicos.php'); ?>

    <!-- fim serviços -->

    <!-- inicio galeria -->

    <?php require_once('conteudo/galeria.php'); ?>

    <!-- fim galeria -->

    <!-- inicio agendamentos -->

    <?php require_once('conteudo/agendamentos.php'); ?>


    <!-- fim agendamentos -->

    <!-- inicio depoimentos -->

    <?php require_once('conteudo/depoimentos.php'); ?>

    <!-- fim depoimentos -->


    <!-- Inicio produtos -->
    <?php require_once('conteudo/produtos.php'); ?>

    <!-- fim produtos -->

  </main>




  <!-- inicio localização -->

  <?php require_once('conteudo/localizacao.php') ?>

  <!-- fim localização -->

  <!-- Inicio rodapé -->
  <?php require_once('conteudo/rodape.php') ?>

  <!-- Fim Rodapé -->

  <script src="https://code.jquery.com/jquery-3.7.1.min.js"
    integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

  <script src="js/slick.min.js"></script>

  <script src="js/wow.min.js"></script>

  <script src="js/script.js"></script>





</body>


</html>